<?xml version="1.0" encoding="utf-8"?><Database Name="Sports" Class="SportsDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CSG-028636\SQL2K14EXPRESS;Initial Catalog=Sports;Integrated Security=True" SettingsObjectName="SportsDataAccess.Properties.Settings" SettingsPropertyName="SportsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GameInfo" Member="GameInfos">
    <Type Name="GameInfo">
      <Column Name="game_key" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="game_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="season" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="GameInfo_LeagueInfo" Member="LeagueInfos" ThisKey="game_key" OtherKey="game_key" Type="LeagueInfo" />
      <Association Name="GameInfo_PlayerInfo" Member="PlayerInfos" ThisKey="game_key" OtherKey="game_key" Type="PlayerInfo" />
    </Type>
  </Table>
  <Table Name="dbo.LeagueInfo" Member="LeagueInfos">
    <Type Name="LeagueInfo">
      <Column Name="league_key" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="league_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="game_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LeagueInfo_TeamInfo" Member="TeamInfos" ThisKey="league_key" OtherKey="league_key" Type="TeamInfo" />
      <Association Name="LeagueInfo_NBAAdvTotalPlayerStat" Member="NBAAdvTotalPlayerStats" ThisKey="league_key" OtherKey="league_key" Type="NBAAdvTotalPlayerStat" />
      <Association Name="LeagueInfo_WeekInfo" Member="WeekInfos" ThisKey="league_key" OtherKey="league_key" Type="WeekInfo" />
      <Association Name="LeagueInfo_MatchupInfo" Member="MatchupInfos" ThisKey="league_key" OtherKey="league_key" Type="MatchupInfo" />
      <Association Name="GameInfo_LeagueInfo" Member="GameInfo" ThisKey="game_key" OtherKey="game_key" Type="GameInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeamInfo" Member="TeamInfos">
    <Type Name="TeamInfo">
      <Column Name="team_key" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="team_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="league_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="manager" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TeamInfo_MatchupInfo" Member="MatchupInfos" ThisKey="team_key" OtherKey="team1_key" Type="MatchupInfo" />
      <Association Name="TeamInfo_MatchupInfo1" Member="MatchupInfos1" ThisKey="team_key" OtherKey="team2_key" Type="MatchupInfo" />
      <Association Name="TeamInfo_NBAAdvWeeklyPlayerStat" Member="NBAAdvWeeklyPlayerStats" ThisKey="team_key" OtherKey="team_key" Type="NBAAdvWeeklyPlayerStat" />
      <Association Name="TeamInfo_NBAWeeklyPlayerStat" Member="NBAWeeklyPlayerStats" ThisKey="team_key" OtherKey="team_key" Type="NBAWeeklyPlayerStat" />
      <Association Name="TeamInfo_NBAWeeklyTeamStat" Member="NBAWeeklyTeamStats" ThisKey="team_key" OtherKey="team_key" Type="NBAWeeklyTeamStat" />
      <Association Name="LeagueInfo_TeamInfo" Member="LeagueInfo" ThisKey="league_key" OtherKey="league_key" Type="LeagueInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerInfo" Member="PlayerInfos">
    <Type Name="PlayerInfo">
      <Column Name="player_key" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="player_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="game_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PlayerInfo_NBAAdvTotalPlayerStat" Member="NBAAdvTotalPlayerStats" ThisKey="player_key" OtherKey="player_key" Type="NBAAdvTotalPlayerStat" />
      <Association Name="PlayerInfo_NBAAdvWeeklyPlayerStat" Member="NBAAdvWeeklyPlayerStats" ThisKey="player_key" OtherKey="player_key" Type="NBAAdvWeeklyPlayerStat" />
      <Association Name="PlayerInfo_NBAWeeklyPlayerStat" Member="NBAWeeklyPlayerStats" ThisKey="player_key" OtherKey="player_key" Type="NBAWeeklyPlayerStat" />
      <Association Name="GameInfo_PlayerInfo" Member="GameInfo" ThisKey="game_key" OtherKey="game_key" Type="GameInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NBAAdvTotalPlayerStats" Member="NBAAdvTotalPlayerStats">
    <Type Name="NBAAdvTotalPlayerStat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="player_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="league_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="weeks_started" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_ppg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_rpg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_apg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_spg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_bpg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_pct_contribution" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_points_win" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="total_rebounds_win" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="total_assists_win" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="total_steals_win" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="total_blocks_win" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="total_wins" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="total_win_ppg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_win_rpg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_win_apg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_win_spg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_win_bpg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total_win_pct_contribution" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="win_pct_contribution_per_week" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="pct_contribution_per_win" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="player_win_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="LeagueInfo_NBAAdvTotalPlayerStat" Member="LeagueInfo" ThisKey="league_key" OtherKey="league_key" Type="LeagueInfo" IsForeignKey="true" />
      <Association Name="PlayerInfo_NBAAdvTotalPlayerStat" Member="PlayerInfo" ThisKey="player_key" OtherKey="player_key" Type="PlayerInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WeekInfo" Member="WeekInfos">
    <Type Name="WeekInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="league_key" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="week" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isShortWeek" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isLongWeek" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isPlayoffs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isConsolation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="endDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="lastLoadDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="WeekInfo_MatchupInfo" Member="MatchupInfos" ThisKey="id" OtherKey="week_id" Type="MatchupInfo" />
      <Association Name="WeekInfo_NBAAdvWeeklyPlayerStat" Member="NBAAdvWeeklyPlayerStats" ThisKey="id" OtherKey="week_id" Type="NBAAdvWeeklyPlayerStat" />
      <Association Name="WeekInfo_NBAWeeklyPlayerStat" Member="NBAWeeklyPlayerStats" ThisKey="id" OtherKey="week_id" Type="NBAWeeklyPlayerStat" />
      <Association Name="WeekInfo_NBAWeeklyTeamStat" Member="NBAWeeklyTeamStats" ThisKey="id" OtherKey="week_id" Type="NBAWeeklyTeamStat" />
      <Association Name="LeagueInfo_WeekInfo" Member="LeagueInfo" ThisKey="league_key" OtherKey="league_key" Type="LeagueInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchupInfo" Member="MatchupInfos">
    <Type Name="MatchupInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="week_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="league_key" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="team1_key" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="team2_key" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LeagueInfo_MatchupInfo" Member="LeagueInfo" ThisKey="league_key" OtherKey="league_key" Type="LeagueInfo" IsForeignKey="true" />
      <Association Name="TeamInfo_MatchupInfo" Member="TeamInfo" ThisKey="team1_key" OtherKey="team_key" Type="TeamInfo" IsForeignKey="true" />
      <Association Name="TeamInfo_MatchupInfo1" Member="TeamInfo1" ThisKey="team2_key" OtherKey="team_key" Type="TeamInfo" IsForeignKey="true" />
      <Association Name="WeekInfo_MatchupInfo" Member="WeekInfo" ThisKey="week_id" OtherKey="id" Type="WeekInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NBAAdvWeeklyPlayerStats" Member="NBAAdvWeeklyPlayerStats">
    <Type Name="NBAAdvWeeklyPlayerStat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="player_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="team_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="week_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ppg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="rpg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="apg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="spg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="bpg_pct" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="pct_contribution" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="win_pct_contribution" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="pct_contribution_of_wins" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="PlayerInfo_NBAAdvWeeklyPlayerStat" Member="PlayerInfo" ThisKey="player_key" OtherKey="player_key" Type="PlayerInfo" IsForeignKey="true" />
      <Association Name="TeamInfo_NBAAdvWeeklyPlayerStat" Member="TeamInfo" ThisKey="team_key" OtherKey="team_key" Type="TeamInfo" IsForeignKey="true" />
      <Association Name="WeekInfo_NBAAdvWeeklyPlayerStat" Member="WeekInfo" ThisKey="week_id" OtherKey="id" Type="WeekInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NBAWeeklyPlayerStats" Member="NBAWeeklyPlayerStats">
    <Type Name="NBAWeeklyPlayerStat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="player_key" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="team_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="week_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="games_played" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="games_missed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rebounds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="assists" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="steals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="blocks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="PlayerInfo_NBAWeeklyPlayerStat" Member="PlayerInfo" ThisKey="player_key" OtherKey="player_key" Type="PlayerInfo" IsForeignKey="true" />
      <Association Name="TeamInfo_NBAWeeklyPlayerStat" Member="TeamInfo" ThisKey="team_key" OtherKey="team_key" Type="TeamInfo" IsForeignKey="true" />
      <Association Name="WeekInfo_NBAWeeklyPlayerStat" Member="WeekInfo" ThisKey="week_id" OtherKey="id" Type="WeekInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NBAWeeklyTeamStats" Member="NBAWeeklyTeamStats">
    <Type Name="NBAWeeklyTeamStat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="team_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="week_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="games_played" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="games_missed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="assists" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rebounds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="steals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="blocks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="points_win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="rebounds_win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="assists_win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="steals_win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="blocks_win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="points_tie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="rebounds_tie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="assists_tie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="steals_tie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="blocks_tie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TeamInfo_NBAWeeklyTeamStat" Member="TeamInfo" ThisKey="team_key" OtherKey="team_key" Type="TeamInfo" IsForeignKey="true" />
      <Association Name="WeekInfo_NBAWeeklyTeamStat" Member="WeekInfo" ThisKey="week_id" OtherKey="id" Type="WeekInfo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>